### ISSUE TITLE
Please help me . I can not connect using MySQL db

### ISSUE THREAD

**Issue by Zak-VisibleOne** [lenard123/fastfood-pos-csharp#5]
![image](https://user-images.githubusercontent.com/83205542/166929683-bd6e0c19-47a0-4d49-adab-7f6303962ea0.png)
![image](https://user-images.githubusercontent.com/83205542/166929756-46e65d3f-93d7-4a20-bb78-3cc577b29547.png)

**Comment by Zak-VisibleOne** [comment]
![image](https://user-images.githubusercontent.com/83205542/166930009-5ed85bd8-45c1-4b6e-9392-3b177a1150a2.png)

**Comment by lenard123** [comment]
Make sure that your MySQL Server is running.

Alternatively you can use the MSACCESS instead.
